name = "applications"
description = "Access to installed applications"
caveat = "This feature provides write access to the user's applications folder"

[files.user]
rw = ["$XDG_DATA_HOME/applications"]

[files.platform]
ro = ["/usr/share/applications"]
