name = "bin"
description = "Provide all host binaries and libraries to the sandbox"
caveat = "All host binaries and libraries are accessible in the sandbox"
binaries = ["/usr/bin"]

[files.platform]
ro = ["/usr/x86_64-pc-linux-gnu/bin", "/etc/alternatives"]
