name = "debug-shell"
description = "Drop into a debug shell"
conditional = "command -v /usr/bin/sh"
requires = ["shell"]
conflicts = ["daemon"]
binaries = ["ls", "sh", "cat"]
sandbox_args = ["#", "sh", "!"]
