name = "dri"
description = "DRI for accelerated video rendering"
devices = ["/dev/dri"]

[libraries]
directories = ["dri", "gbm"]
files = ["libMesa*", "libGL*", "libEGL*"]

[files]
platform.ro = [
  "/sys/devices/pci0000:00",
  "/sys/dev/char",
  "/etc/OpenCL/",
]

resources.ro = [
  "/usr/share/glvnd",
  "/usr/share/libdrm",
  "/usr/share/drirc.d",
]
