name = "dri"
description = "DRI for accelerated video rendering"
devices = ["/dev/dri"]

[libraries]
files = ["libMesa*", "libGL*", "libEGL*"]
directories = ["dri", "gbm"]

[files.platform]
ro = ["/sys/dev/char", "/sys/devices/pci0000:00", "/etc/OpenCL/"]

[files.resources]
ro = ["/usr/share/libdrm", "/usr/share/drirc.d", "/usr/share/glvnd"]
