name = "dri"
description = "DRI for accelerated video rendering"
devices = ["/dev/udmabuf", "/dev/dri"]

[libraries]
files = ["libMesa*", "libGL*", "libEGL*"]
directories = ["dri", "gbm"]

[files.platform]
ro = [
    "/sys/dev/char", "/sys/devices/pci0000:00", "/etc/OpenCL/",
    "/usr/share/glvnd", "/usr/share/drirc.d", "/usr/share/libdrm"
]
