name = "electron"
description = "For Chromium/Electron applications"
requires = ["gtk3"]
namespaces = ["User"]
devices = ["/dev/null", "/dev/urandom", "/dev/shm"]
libraries.files = ["libsoftokn3*", "libfreeblpriv3*", "libsmime3*", "libnss*"]
