name = "electron"
description = "For Chromium/Electron applications"
requires = ["gtk3"]
devices = ["/dev/urandom", "/dev/shm", "/dev/null"]
namespaces = ["User"]

[libraries]
files = ["libsoftokn3*", "libsmime3*", "libfreeblpriv3*", "libnss*"]
