name = "flatpak-spawn"
description = "Use Antimony-Spawn to permit sandboxes to run other applications under Antimony."
binaries = ["bwrap", "bash", "ldd", "$AT_HOME/utilities/antimony-spawn=/usr/bin/flatpak-spawn"]
namespaces = ["User"]

[files.platform]
ro = ["/etc/antimony.toml", "/etc/antimony.d"]

[files.platform]
ro = ["/usr/share/antimony/db/antimony.db"]
