name = "flatpak-spawn"
description = "Use Antimony-Spawn to permit sandboxes to run other applications under Antimony."
binaries = ["$AT_HOME/utilities/antimony-spawn=/usr/bin/flatpak-spawn", "bwrap", "bash"]
namespaces = ["User"]

[files.platform]
ro = ["/etc/antimony.toml", "/etc/antimony.d"]
