name = "fonts"
description = "Provide host fonts and config."

[files.user]
ro = ["$XDG_DATA_HOME/fonts", "$HOME/.fonts", "$XDG_CONFIG_HOME/fontconfig", "$XDG_DATA_HOME/fontconfig"]

[files.platform]
ro = ["/usr/share/fontconfig", "/etc/fonts", "/usr/share/fonts"]
