name = "glycin"
description = "Gnome Image Loading."
requires = ["flatpak-spawn", "gir"]
conflicts = ["hardened_malloc"]
binaries = ["prlimit"]

[libraries]
files = ["libglycin*", "librsvg*"]
directories = ["glycin-loaders"]

[files.resources]
ro = ["/usr/share/glycin-loaders/", "/usr/include/glycin-2/", "/usr/include/glycin-gtk4-2/"]
