name = "gst"
description = "GStreamer for video/audio playback"
requires = ["gir", "passwd", "python"]
files.resources.ro = ["/usr/share/gstreamer-1.0/"]

[libraries]
directories = ["gstreamer-1.0"]
files = ["libgst*"]
