name = "gst"
description = "GStreamer for video/audio playback"
requires = ["passwd", "python", "gir"]

[libraries]
files = ["libgst*"]
directories = ["gstreamer-1.0"]

[files.resources]
ro = ["/usr/share/gstreamer-1.0/"]
