name = "gtk4"
description = "For GTK4 applications"
requires = ["dri", "vulkan", "gdk-pixbuf", "mime", "accessibility", "wayland", "fonts", "themes"]

[environment]
GTK_USE_PORTAL = "1"
GTK_A11Y = "none"

[libraries]
files = ["libgdk-4*", "libgtk-4*"]
directories = ["gtk-4.0", "tinysparql-3.0"]

[ipc]
owns = ["{desktop}"]

[files.user]
ro = ["$HOME/.gtkrc-2.0", "$XDG_CONFIG_HOME/gtkrc", "$XDG_CONFIG_HOME/gtk-2.0", "$XDG_CONFIG_HOME/gtkrc-2.0", "$XDG_CONFIG_HOME/gtk-4.0"]

[files.platform]
ro = ["/etc/xdg/gtk-4.0/"]

[files.resources]
ro = ["/usr/share/glib-2.0", "/usr/share/gtk", "/usr/share/gtk-2.0", "/usr/share/gtk-4.0"]
