name = "locale"
description = "Provide localization information"

libraries.directories = ["locale"]

[files]
platform.ro = [
  "/etc/localtime",
  "/usr/share/zoneinfo",
  "/usr/share/locale"
]

[environment]
LANG = "$LANG"
