name = "network"
description = "Give applications network connectivity."
namespaces = ["Net"]

[files.platform]
ro = ["/etc/ssl", "/etc/hosts", "/etc/resolv.conf", "/usr/share/ssl", "/etc/nsswitch.conf", "/usr/share/pki", "/etc/gai.conf", "/etc/pki", "/usr/share/ca-certificates", "/etc/ca-certificates", "/etc/host.conf"]
