name = "passwd"
description = "Provide a /etc/passwd"

[files.direct.ro]
"/etc/group" = """
antimony:x:$UID:antimony
"""
"/etc/passwd" = """
antimony:x:$UID:$UID:Antimony:/home/antimony:/usr/bin/sh
"""
