name = "pipewire"
description = "The PipeWire socket for video/audio."

[libraries]
files = ["libpipewire*"]
directories = ["pipewire-0.3", "pulseaudio", "spa-0.2"]

[files.user]
ro = ["$XDG_CONFIG_HOME/pulse"]

[files.platform]
ro = ["/etc/pipewire", "$XDG_RUNTIME_DIR/pipewire-0", "$XDG_RUNTIME_DIR/pulse"]

[files.resources]
ro = ["/usr/share/pipewire"]
