name = "qt5"
description = "Provide necessary files for QT5 applications"

requires = ["wayland", "fonts", "themes", "mime", "dri", "locale"]

[libraries]
directories = ["qt/plugins", "qt/qml"]
files = ["libQt5*"]
roots = ["/usr/lib/qt"]

[files]
user.ro = [
  "$XDG_CONFIG_HOME/kdedefaults",
  "$XDG_CONFIG_HOME/breezerc",
  "$XDG_CONFIG_HOME/kdeglobals",
  "$XDG_CONFIG_HOME/Trolltech.conf",
  "$XDG_CONFIG_HOME/kde.org"
]
resources.ro = [
  "/usr/share/qt6"
]

[environment]
"QT_QPA_PLATFORM" = "wayland"
