name = "rust-devel"
description = "Provide Rust and its associated development tools."
requires = ["gcc", "hostname"]
binaries = ["cargo-clippy", "ld.lld", "rustc", "rustdoc", "nm", "clippy-driver", "cargo-fmt", "rustfmt", "cargo", "rustup", "strip"]

[environment]
CARGO_HOME = "$CARGO_HOME"
RUSTUP_HOME = "$RUSTUP_HOME"

[libraries]
no_sof = true

[files.user]
rw = ["$RUSTUP_HOME", "$CARGO_HOME"]
