name = "rust-devel"
description = "Provide Rust and its associated development tools."
requires = ["gcc", "hostname"]
libraries.no_sof = true

binaries = [
  "cargo",
  "cargo-clippy",
  "cargo-fmt",
  "clippy-driver",
  "rustc",
  "rustdoc",
  "rustfmt",
  "rustup",
  "nm",
  "ld.lld",
  "strip",
]

[files.user]
rw = ["$RUSTUP_HOME", "$CARGO_HOME"]

[environment]
"RUSTUP_HOME" = "$RUSTUP_HOME"
"CARGO_HOME" = "$CARGO_HOME"
