name = "secrets"
description = "Provide the org.freedesktop.secrets bus for storing secrets in the host keychain"

[ipc]
portals = ["Secret"]
talk = ["org.freedesktop.secrets"]
call = [
  "org.freedesktop.secrets=org.freedesktop.Secret.Service.*@/org/freedesktop/secrets",
  "org.freedesktop.secrets=org.freedesktop.Secret.Collection.*@/org/freedesktop/secrets/aliases/default"
]
