name = "shell"
description = "Provide /usr/bin/sh"
requires = ["passwd"]
binaries = ["/usr/bin/sh"]

[environment]
TERM = "$TERM"

[files.platform]
ro = ["/etc/profile.env", "/etc/profile", "/usr/share/terminfo", "/etc/profile.d", "/etc/bash"]
