name = "udev"
description = "Device information"
caveat = "This provides access to /sys, allowing the sandbox to see all devices."
binaries = ["dmidecode", "udevadm"]

[files.platform]
ro = ["/etc/udev", "/sys", "/usr/share/hwdata"]
