name = "vulkan"
description = "Vulkan libraries and configuration."

[libraries]
files = ["libVkLayer*", "libvulkan*"]

[files.platform]
ro = ["/etc/vulkan"]

[files.resources]
ro = ["/usr/share/vulkan"]
