name = "wayland"
description = "Provide the wayland socket."

[environment]
XDG_CURRENT_DESKTOP = "$XDG_CURRENT_DESKTOP"
XDG_SESSION_TYPE = "wayland"
WAYLAND_DISPLAY = "$WAYLAND_DISPLAY"
DESKTOP_SESSION = "$DESKTOP_SESSION"

[libraries]
files = ["libwayland*"]

[files.user]
ro = ["$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"]

[files.platform]
ro = ["/usr/share/X11/xkb", "/usr/share/xkeyboard-config-2"]
