name = "webkit"
description = "WebKit for rendering web-content"
requires = ["gio", "gir"]

[libraries]
files = ["libjavascriptcoregtk*", "libwebkitgtk*"]
directories = ["webkitgtk-6.0"]

[ipc]
portals = ["Realtime"]
