name = "webkit"
description = "WebKit for rendering web-content"
requires = ["gir", "gio"]

[libraries]
directories = ["webkitgtk-6.0"]
files = ["libjavascriptcoregtk*", "libwebkitgtk*"]

[ipc]
portals = ["Realtime"]
