name = "wine"
description = "Run Windows applications under Wine"
notes = """
This feature, on its own, simply runs whatever you pass under wine. However, the usual
setup for Windows applications usually requires running an installer (Under wine), then
running the application from the Wine prefix (Also under wine).

Therefore, the procedure for running something like Battle.Net (battle.toml), is
1. Pass through the installer and drop into a debug shell via `antimony run battle.net --ro ~/Downloads/battle.net.exe --features debug-shell
2. Run the installer via wine in the sandbox (i.e `wine ~/Downloads/battle.net.exe`)
3. Exit out of the sandbox, then run the profile normally.
"""
caveat = "This feature requires vast permissions"
requires = ["vulkan", "bin", "locale", "dri", "lib", "wayland", "fonts", "ld", "xorg"]
conflicts = ["hardened_malloc"]
seccomp = "Disabled"
devices = ["/dev"]
sandbox_args = ["wine"]

[libraries]
roots = ["/usr/lib32"]

[files.platform]
ro = ["/var/lib/dbus/machine-id", "/sys", "/run/udev"]

[files.resources]
ro = ["/usr/share/wine"]
