notes = """
You can run antimony inside antimony, if you'd like. Note that simply stacking more of the same security measure
does not constitute defense-in-depth; this is used solely for packaging.
"""
features = ["bin", "lib", "network"]
conflicts = ["hardened_malloc"]
seccomp = "Disabled"
binaries = ["xdg-dbus-proxy", "ldd", "bwrap"]
devices = ["/dev"]
namespaces = ["All"]
preserve_env = true
ignored_exit_codes = [2]

[ipc]
system_bus = true
user_bus = true

[files.platform]
rw = ["/home", "/usr/share", "/run", "/var", "/sys", "/etc", "/tmp"]

[files.resources]
rw = ["/usr/share/antimony"]
