id = "calibre-gui"
features = ["python", "kf6"]
binaries = ["calibredb", "ebook-*", "fetch-ebook-metadata", "pdftohtml", "web2disk", "lrf*", "calibre-*", "markdown-calibre"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser"]

[libraries]
files = ["libxxhash*"]
directories = ["calibre"]
