path = "/opt/cryptomator/bin/cryptomator"
id = "org.cryptomator.Cryptomator"
features = ["gtk3", "xorg"]
binaries = ["sh"]
libraries.files = ["libpthread*", "librt*", "libgthread*", "libX*", "libappindicator*"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser"]
