notes = "You cannot actually mount volumes though antimony, as that requires privilege."
path = "/opt/cryptomator/bin/cryptomator"
id = "org.cryptomator.Cryptomator"
features = ["gtk3", "xorg"]
binaries = ["sh"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser"]

[libraries]
files = ["librt*", "libappindicator*", "libX*", "libpthread*", "libgthread*"]
