id = "org.deskflow.deskflow"
features = ["qt6", "qt6-plugins", "qt6-qml", "network", "tray"]
binaries = ["deskflow-core"]

[home]
policy = "Enabled"

[ipc]
portals = ["RemoteDesktop", "InputCapture"]

[libraries]
files = ["/usr/lib/libnss*"]
