id =  "com.mattjakeman.ExtensionManager"

features = ["libadwaita", "network", "gio"]

[ipc]
portals = ["Documents"]
talks = ["org.gnome.Shell.Extensions"]
calls = ["org.gnome.Shell.Extensions=org.gnome.Shell.Extensions.*@/org/gnome/Shell/Extensions"]
