features = ["python", "gir", "tray", "gdk-pixbuf", "kf6"]

[ipc]
system_bus = true

[files.user]
rw = ["$XDG_CONFIG_HOME/firewall"]

[files.platform]
ro = ["/etc/firewall"]

[libraries]
files = ["libnotify*"]
