id = "com.github.neithern.g4music"
features = ["libadwaita", "pipewire", "vaapi", "gst", "mpris"]

[home]
policy = "Enabled"

[ipc]
portals = ["Background", "FileChooser", "Inhibit"]

[files.user]
rw = ["Music"]
