id = "io.github.input_leap.input-leap"
features = ["network", "tray", "qt6-qml", "qt6", "qt6-plugins"]
binaries = ["input-leapc", "input-leaps"]

[home]
policy = "Enabled"

[ipc]
portals = ["RemoteDesktop", "InputCapture"]

[libraries]
files = ["/usr/lib/libnss*"]
