path = "/usr/lib/invidious/invidious"
dir = "/usr/lib/invidious"
features = ["network", "locale"]
binaries = ["sh"]

[home]
name = "invidious/home"
policy = "Enabled"

[files.resources]
ro = ["$XDG_DATA_HOME/antimony/invidious/invidious.yml=/etc/invidious.yml"]

[libraries]
files = ["libnss*"]
directories = ["invidious"]

[[hooks.pre]]
type = "Profile"
content = "postgresql"
arguments = ["--home-name", "invidious/db"]
attach = true

[[hooks.pre]]
type = "Profile"
content = "$XDG_DATA_HOME/antimony/invidious/invidious_companion"
arguments = ["--env", "SERVER_SECRET_KEY=1234567890abcdef", "--features", "network"]
attach = true

[[hooks.pre]]
type = "Shell"
content = """
echo "Waiting for DB"
while ! nc -z localhost 5432; do
  sleep 1
done

echo "Waiting for Companion"
while ! nc -z localhost 8282; do
  sleep 1
done
"""
