id = "org.keepassxc.KeePassXC"
features = ["gocryptfs", "qt6", "kf6"]
ignored_exit_codes = [139]

[home]
policy = "Enabled"

[ipc]
portals = ["GlobalShortcuts", "FileChooser"]

[libraries]
files = ["libpcsclite*"]
