id = "io.missioncenter.MissionCenter"
features = ["libadwaita", "network", "gio", "cgroup", "passwd", "sys", "applications"]
binaries = ["/usr/share/antimony/utilities/antimony-spawn=/app/bin/missioncenter-spawner", "missioncenter-magpie", "sh"]
devices = ["/dev/udmabuf"]
namespaces = ["Pid"]

[files.platform]
ro = ["/run/udev/data"]

[files.links]
"/usr/bin/missioncenter-magpie" = "/usr/bin/missioncenter-magpie-glibc"

[libraries]
files = ["libdrm*"]
