id = "io.missioncenter.MissionCenter"
features = ["libadwaita", "network", "gio", "cgroup", "passwd", "sys", "applications"]
binaries = ["/usr/bin/missioncenter-magpie=/usr/bin/missioncenter-magpie-glibc", "sh", "missioncenter-magpie", "/usr/share/antimony/utilities/antimony-spawn=/app/bin/missioncenter-spawner"]
devices = ["/dev/udmabuf"]
namespaces = ["Pid"]

[files.platform]
ro = ["/run/udev/data"]

[libraries]
files = ["libdrm*"]
