path = "io.gitlab.news_flash.NewsFlash"
features = ["libadwaita", "mpris", "libclapper", "network", "webkit", "xdg-open"]

[home]
policy = "Enabled"

[ipc]
portals = ["Background", "FileChooser", "Inhibit"]
owns = ["org.mpris.MediaPlayer2.Newsflash"]
