id = "com.obsproject.Studio"
features = ["python", "pipewire", "sdl", "vaapi", "qt6", "tray"]
seccomp = "Permissive"
binaries = ["obs-ffmpeg-mux"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser", "ScreenCast"]

[libraries]
files = ["libobs*"]
directories = ["obs-plugins"]
