id = "opensnitch_ui"
features = ["qt5", "python", "tray"]
namespaces = ["Pid"]

[home]
policy = "Enabled"

[files.platform]
rw = ["/tmp"]

[[hooks.pre]]
type = "Program"
name = "sleep"
content = "sleep"
arguments = ["0.5"]
