path = "tubefeeder"
id = "de.schmidhuberj.tubefeeder"
features = ["libadwaita", "network", "libclapper", "gio", "libpeas"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser"]
owns = ["org.mpris.MediaPlayer2.tubefeeder.*"]
