path = "tubefeeder"
id = "de.schmidhuberj.tubefeeder"
features = ["libadwaita", "gio", "libclapper", "network", "libpeas"]
inherits = ["default"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser"]
owns = ["org.mpris.MediaPlayer2.tubefeeder.*"]
