id = "org.kde.plasma-systemmonitor"
features = ["cgroup", "kf6", "ksysguard", "network"]
libraries.files = ["libPlasmaSystemMonitor*"]
namespaces = ["Pid"]

[home]
policy = "Enabled"

[ipc]
talks = ["org.kde.ksystemstats", "org.kde.ksystemstats1.*"]
owns = ["org.kde.plasma-systemmonitor"]

[files.platform]
ro = ["/sys"]
