id = "org.kde.plasma-systemmonitor"
features = ["ksysguard", "cgroup", "network", "kf6"]
namespaces = ["Pid"]

[home]
policy = "Enabled"

[ipc]
talks = ["org.kde.ksystemstats", "org.kde.ksystemstats1.*"]
owns = ["org.kde.plasma-systemmonitor"]

[files.platform]
ro = ["/sys"]

[libraries]
files = ["libPlasmaSystemMonitor*"]
