path = "postgres"
features = ["network", "locale"]
binaries = ["createuser", "createdb", "initdb"]
arguments = ["-D", "/home/antimony/db"]

[home]
policy = "Enabled"

[files]
temp = ["/run/postgresql"]
