path = "postgres"
features = ["network", "locale"]
binaries = ["createdb", "initdb", "createuser"]
arguments = ["-D", "/home/antimony/db"]

[home]
policy = "Enabled"

[files]
temp = ["/run/postgresql"]
