features = ["network"]

[home]
policy = "Enabled"

[libraries]
files = ["libstdc++*", "libsecret*"]

[configuration.run]
arguments = ["start", "--no-daemon"]

[[hooks.pre]]
type = "Shell"
content = """sqlite3 $ANTIMONY_HOME/.local/state/proton-drive-sync/state.db "DELETE FROM flags WHERE name GLOB 'running_pid*';""""
