features = ["network"]
libraries.files = ["libsecret*"]

[home]
policy = "Enabled"

[configuration.run]
arguments = ["start", "--no-daemon"]

[[hooks.pre]]
type = "Program"
content = "sleep"
arguments = ["5"]

[[hooks.pre]]
type = "Shell"
content = "sqlite3 $ANTIMONY_HOME/.local/state/proton-drive-sync/state.db \"DELETE FROM flags WHERE name GLOB 'running_pid*';\""
