features = ["shell", "xdg-open", "electron", "network"]
arguments = ["--ozone-platform=wayland"]

[home]
policy = "Enabled"
lock = true

[files.platform]
ro = ["/usr/share/applications/proton-mail.desktop"]
