features = ["network"]
libraries.files = ["libsecret*"]

[home]
policy = "Enabled"

[configuration.run]
arguments = ["start", "--no-daemon"]

[[hooks.pre]]
content = "sleep"
arguments = ["5"]

[[hooks.pre]]
content = "sqlite3"
arguments = ["$ANTIMONY_HOME/.local/state/proton-drive-sync/state.db", "DELETE FROM flags WHERE name GLOB 'running_pid*';"]
