id = "org.gnome.World.Secrets"
features = ["libadwaita", "python", "gtksourceview", "bin", "ld"]
devices = ["/dev/bus/usb"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser"]

[libraries]
files = ["libusb*"]
