features = ["passwd", "network"]
seccomp = "Disabled"
binaries = ["sh"]
arguments = ["-D"]

[home]
name = "sshd/home"
policy = "Enabled"

[files.resources]
ro = ["$XDG_DATA_HOME/antimony/sshd/etc=/etc/ssh"]

[libraries]
directories = ["ssh"]
