features = ["vulkan", "bin", "passwd", "network", "wayland", "ld", "pipewire", "xorg", "tray"]
conflicts = ["hardened_malloc"]
seccomp = "Disabled"
devices = ["/dev"]
namespaces  = ["User"]

[home]
policy = "Enabled"

[ipc]
user_bus = true

[files.platform]
ro = ["/etc/machine-id", "/sys", "/run/udev"]

[files.user]
rw = ["/steam"]

[libraries]
no_sof = true
roots = ["/usr/lib32"]
