features = ["bin", "vulkan", "passwd", "network", "ld", "pipewire", "xorg", "electron", "tray"]
conflicts = ["hardened_malloc"]
inherits = ["default"]
seccomp = "Disabled"
devices = ["/dev"]
new_privileges = true

[home]
policy = "Enabled"

[ipc]
user_bus = true

[files.platform]
ro = ["/etc/machine-id"]

[libraries]
no_sof = true
roots = ["/usr/lib32"]
