features = ["gtk3", "python", "gtksourceview", "network"]

[home]
policy = "Enabled"

[ipc]
system_bus = true
owns = ["org.virt-manager.virt-manager"]

[files.platform]
ro = ["/sys", "/var/run/libvirt"]

[files.resources]
ro = ["/usr/share/osinfo", "/usr/share/misc", "/usr/share/hwdata"]

[libraries]
files = ["libosinfo*", "libvirt*", "libspice-client*"]
