path = "/usr/lib/zed/zed-editor"
id = "dev.zed.Zed"
features = ["dri", "vulkan", "fonts", "shell", "wayland"]

[home]
policy = "Enabled"

[ipc]
portals = ["FileChooser", "Settings", "Documents"]

[files]
passthrough = "rw"
