#!/bin/bash
set -e

RECIPE="${1}"
if [[ -z $RECIPE ]]; then
  RECIPE="release"
fi

TARGET="x86_64-unknown-linux-gnu"

if [[ "${RECIPE}" == "pgo" ]]; then
  ./pgo
  RECIPE="release"
elif [[ "${RECIPE}" == "bolt" ]]; then
  ./bolt
  RECIPE="release"
  SUFFIX="-bolt-optimized"
else
  RUSTFLAGS="-Ctarget-cpu=native" cargo build \
    --profile $RECIPE \
    --workspace \
    --target $TARGET \
    -Z build-std=std,panic_abort

  if [[ "${RECIPE}" == "dev" ]]; then
      RECIPE="debug"
  fi
fi

echo "Copying binaries"
if [[ ! -d /usr/share/antimony/utilities ]]; then
  sudo mkdir -p /usr/share/antimony/utilities
fi

sudo cp --remove-destination -v "target/$TARGET/$RECIPE/antimony${SUFFIX}" "/usr/bin/antimony"
sudo cp --remove-destination -v "target/$TARGET/$RECIPE/antimony-spawn${SUFFIX}" "/usr/share/antimony/utilities/antimony-spawn"
sudo cp --remove-destination -v "target/$TARGET/$RECIPE/antimony-monitor${SUFFIX}" "/usr/share/antimony/utilities/antimony-monitor"
sudo cp --remove-destination -v "target/$TARGET/$RECIPE/antimony-dumper${SUFFIX}" "/usr/share/antimony/utilities/antimony-dumper"
sudo cp --remove-destination -v "target/$TARGET/$RECIPE/antimony-open${SUFFIX}" "/usr/share/antimony/utilities/antimony-open"
sudo cp --remove-destination -v "target/$TARGET/$RECIPE/notify${SUFFIX}" "/usr/share/antimony/utilities/antimony-notify"

echo "Setting SetUID"
exec="/usr/bin/antimony"
sudo chown antimony:antimony $exec
sudo chmod u+s $exec
sudo chmod o+x $exec

echo "Removing old config"
sudo rm -fr /usr/share/antimony/{features,profiles}

echo "Setting up config"
if [[ ! -d /usr/share/antimony/config ]]; then
  sudo mkdir /usr/share/antimony/config
fi

sudo cp -r config/features /usr/share/antimony
sudo cp -r config/profiles /usr/share/antimony

sudo cp config/default.toml /usr/share/antimony/config
sudo cp config/feature.toml /usr/share/antimony/config
sudo cp config/new.toml /usr/share/antimony/config

sudo chown -R antimony:antimony /usr/share/antimony
sudo setcap cap_audit_read+ep /usr/share/antimony/utilities/antimony-monitor
sudo setcap cap_sys_ptrace+ep /usr/share/antimony/utilities/antimony-dumper

./deploy-completions "${TARGET}/${RECIPE}"
