#!/bin/sh

target/$1/antimony_completions
sudo cp completions/antimony.bash /usr/share/bash-completion/completions
sudo cp completions/antimony.fish /usr/share/fish/vendor_completions.d
sudo cp completions/_antimony /usr/share/zsh/site-functions
