# This file contains global configuration for Antimony itself.

# For the use of /tmp as the SOF backing store.
# Can be set at runtime by setting AT_FORCE_TEMP to anything besides 0
# force_temp = false

# Disregard user configurations and ignore the command line.
# Can be set at runtime by setting AT_SYSTEM_MODE to anything besides 0
# system_mode = false

# Automatically refresh profiles if they fail to run and re-try execution.
# auto_refresh = false

# A set of user names that do not need to validate privilege via Polkit for
# privileged operations (i.e. modifying the feature set, seccomp, or this file)
# privileged_users = []

# The backend for configurations (i.e. Profiles and Features)
# Updating this value directly does not actually switch the existing backends
# contents. You'll want to use `antimony backend` instead.
# config_store = "File"

# The backend for caches
# Updating this value directly does not actually switch the existing backends
# contents. You'll want to use `antimony backend --cache` instead.
# cache_store = "File"
