#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

if [[ -n $CARGO_TARGET_DIR ]]; then
  TARGET=$CARGO_TARGET_DIR
else
  TARGET=$ROOT/target
fi

DOC_GEN="$TARGET/doc"
DOC_OUT="$ROOT/docs"
rm -r "${DOC_GEN}" "${DOC_OUT}"

RUSTDOCFLAGS="-Zunstable-options --enable-index-page" cargo +nightly doc --no-deps --workspace --all-features --exclude utilities
mv $DOC_GEN $DOC_OUT
