#!/bin/sh

VERSION="${1}"
ROOT=$(git rev-parse --show-toplevel)

export CARGO_TARGET_DIR=${ROOT}/target

echo "Compiling Build Script"
cargo build --package utilities --bin antimony_build --bin antimony_completions

./target/debug/antimony_build --recipe release
./target/debug/antimony_completions

fpm -t pacman --depends libseccomp --depends sqlite --depends dbus --version $VERSION
fpm -t deb --depends libseccomp2 --depends sqlite3 --depends libdbus-1-dev --version $VERSION
fpm -t rpm --depends libseccomp --depends sqlite --depends dbus-devel --version $VERSION
