#!/bin/sh

VERSION="${1}"
ROOT=$(git rev-parse --show-toplevel)

if [[ -n $CARGO_TARGET_DIR ]]; then
  TARGET=$CARGO_TARGET_DIR
else
  TARGET=$ROOT/target
fi

echo "Compiling Build Script"
cargo build --package utilities --bin antimony_build --bin antimony_completions

$TARGET/debug/antimony_build --recipe release
$TARGET/release/antimony_completions

fpm -t pacman --depends libseccomp --depends sqlite --depends dbus --version $VERSION
fpm -t deb --depends libseccomp2 --depends sqlite3 --depends libdbus-1-dev --version $VERSION
fpm -t rpm --depends libseccomp --depends sqlite --depends dbus-devel --version $VERSION
