#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

if [[ -n $CARGO_TARGET_DIR ]]; then
  TARGET=$CARGO_TARGET_DIR
else
  TARGET=$ROOT/target
fi

echo "Compiling Build Script"
cargo build --package utilities --bin antimony_build

echo "Building"
$TARGET/debug/antimony_build "${@:2}"
