#!/bin/bash


ROOT=$(git rev-parse --show-toplevel)

if [[ -n $CARGO_TARGET_DIR ]]; then
  TARGET=$CARGO_TARGET_DIR
else
  TARGET=$ROOT/target
fi

echo "Compiling Digester"
cargo build --package utilities --bin antimony_digest

echo "Digesting"
$TARGET/debug/antimony_digest
