#!/bin/bash
set -e

ROOT=$(git rev-parse --show-toplevel)

echo "Compiling Build Script"
cargo build --package utilities --bin antimony_build --bin antimony_digest
DIR=$($ROOT/target/debug/antimony_build "${@:2}")

echo "Digesting Profiles and Features"
if [[ ! -d /usr/share/antimony/db ]]; then
  sudo mkdir -p /usr/share/antimony/db
fi
$ROOT/target/debug/antimony_digest

sudo cp --remove-destination -v $ROOT/config/db/antimony.db /usr/share/antimony/db/antimony.db
sudo chown antimony:antimony -R /usr/share/antimony/db


echo "Copying binaries"
if [[ ! -d /usr/share/antimony/utilities ]]; then
  sudo mkdir -p /usr/share/antimony/utilities
fi

sudo cp --remove-destination -v "$DIR/antimony" "/usr/bin/antimony"
sudo cp --remove-destination -v "$DIR/antimony-spawn" "/usr/share/antimony/utilities/antimony-spawn"
sudo cp --remove-destination -v "$DIR/antimony-monitor" "/usr/share/antimony/utilities/antimony-monitor"
sudo cp --remove-destination -v "$DIR/antimony-dumper" "/usr/share/antimony/utilities/antimony-dumper"
sudo cp --remove-destination -v "$DIR/antimony-open" "/usr/share/antimony/utilities/antimony-open"
sudo cp --remove-destination -v "$DIR/antimony-tracer" "/usr/share/antimony/utilities/antimony-tracer"

sudo cp --remove-destination -v "$DIR/notify" "/usr/share/antimony/utilities/antimony-notify"

echo "Setting SetUID"
exec="/usr/bin/antimony"
sudo chown antimony:antimony $exec
sudo chmod u+s $exec
sudo chmod o+x $exec

echo "Removing old config"
sudo rm -fr /usr/share/antimony/{features,profiles}

echo "Setting up config"
if [[ ! -d /usr/share/antimony/config ]]; then
  sudo mkdir /usr/share/antimony/config
fi

sudo cp $ROOT/config/default.toml /usr/share/antimony/config
sudo cp $ROOT/config/feature.toml /usr/share/antimony/config
sudo cp $ROOT/config/profile.toml /usr/share/antimony/config
sudo cp $ROOT/config/config.toml /usr/share/antimony/config

sudo chown -R antimony:antimony /usr/share/antimony
sudo setcap cap_audit_read+ep /usr/share/antimony/utilities/antimony-monitor
sudo setcap cap_sys_ptrace+ep /usr/share/antimony/utilities/antimony-dumper

"${DIR}/antimony_completions"
sudo cp $ROOT/completions/antimony.bash /usr/share/bash-completion/completions
sudo cp $ROOT/completions/antimony.fish /usr/share/fish/vendor_completions.d
sudo cp $ROOT/completions/_antimony /usr/share/zsh/site-functions
