#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

if [[ -n $CARGO_TARGET_DIR ]]; then
  TARGET=$CARGO_TARGET_DIR
else
  TARGET=$ROOT/target
fi

cargo build --package utilities --bin antimony_build
if [[ $1 == "builder" ]]; then
  $TARGET/debug/antimony_build "${@:2}"
else
  $TARGET/debug/antimony_build "${@:1}"
fi
