#!/bin/sh

VERSION="${1}"
cargo build --release --workspace
../target/release/antimony_completions

fpm -t pacman --depends libseccomp --depends sqlite --depends dbus --version $VERSION
fpm -t deb --depends libseccomp2 --depends sqlite3 --depends libdbus-1-dev --version $VERSION
fpm -t rpm --depends libseccomp --depends sqlite --depends dbus-devel --version $VERSION
